### ISSUE TITLE
[Discuss] Tag API Has Inconsistent Type Result & Requires "Slug"

### ISSUE THREAD

**Issue by pxwee5** [storyblok/storyblok#12]
**The issue occurs while working with:** (check one with "x")   
- [x] *api.storyblok.com*   

**I'm submitting a ...**  (check one with "x")  
- [x] feature request  

**Current behavior:**
Tags returned from `cdn/tags` is an array of `object`s
Tags returned from `tag_list` in `cdn/story` is an array of `string`s
Tags object does not have `slug`

**Expected behavior:**
I think both of them should return an array of `object`s for consistency purposes. The object should ideally contain the following: name, slug, taggings_count and etc. 

`Slug` is the urgent fix. At the moment there's no way to manage a multi word tag (e.g. Marketing News). If you could introduce a slug for the tags, then we could do stuff like `url.com/tag/marketing-news`. Leaving it as is like `url.com/tag/Marketing News` is non-standard and may cause all kinds of unimaginable error. 

If taggings_count is not required in a story, then it can be omitted. However the returned type should be consistent so that applications do not need to write extra layer of filter to manage the tags. 

I understand that this may affect a lot of existing applications so it could be a hard thing to change. So it is up for discussion.

**Comment by DominikAngerer** [comment]
We see the tags name as "slug" since you may want to translate it later, therefore a key would be much more flexible than having the real string attached directly. You can do a multilanguage solution by combining it with datasources where one key would be the name of your tag and the value of that would be added by a datasource eg. "English Tags"/"Spanish Tags". This way your application will be much more flexible since you can reuse the same tag for multiple languages. Also if the tags will be extended in the future no client will be effected, since they only contain a reference to the actual object.

The reason why there is only the identifier (tagname) in the content entry is that otherwise each request/entry would contain repeated data which could be easily attached by doing one tags call before and combine those to - where the tags call could be also cached and/or kept in memory if done server side and therefore would save additional data. A good example where this was already done would be a website of one of our partners: https://www.netural.com/en/news/

You can see there that they use those tags the allow hashtags above the news - which exist in english as well as in german (you can us the language switch in the menu or simply rewrite the URL from `en` to `de`. They reuse the tag as key and load the data from a translation datasource, since those can easily be exported and translated.

Another point is that it will reduce dependency calculations which results in a much higher scalability for your content - we follow the same idea in the linkings. You can see that one link type result:

```
{
  "id": "984caa42-306f-477d-803d-19b1ce6f51c9",
  "url": "",
  "linktype": "story",
  "fieldtype": "multilink",
  "cached_url": "test"
}
```

You can see that they are also not "the same" as the objects in the `/cdn/tags` API call. The id references the actual content entry linked - the `cached_url` will allow you to access the slug at the moment of publishing and the `url` is available if an external url was entered. For big scale application we recommend to use the `/cdn/tags` call in combination with the shipped id of the link above, since that will result in the most efficient and consistent way of dealing with data.

Hope this covers the question. I'll update the documentation accordingly and add a "best practice" example on the usage to reduce future confusion. Thanks for the report.

**Comment by pxwee5** [comment]
So how would you handle multi word tags in the url? For example if I have a tag named "Cake Recipes". Do I have to write a filter in my app to convert text into slug?

**Comment by DominikAngerer** [comment]
Thats correct - the tag is more focused on setting a specific key.

I guess you're right by saying this is different to other CMS out there, the best about it - if you don't like it you can easily create a new Folder and a new Content Type which has those fields you want included and include them as normal content :) You're still able to use filters - (stories API got filter_by) and therefore you can easily adopt it to your needs. Instead of using the Datasources you could also use them to reference to other Content Types as well.
