### ISSUE TITLE
Set story to published via API

### ISSUE THREAD

**Issue by lancevo** [storyblok/storyblok#15]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com*   
- [X] *api.storyblok.com*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [X] bug report  
- [ ] feature request  

**Current behavior:**
When I make Post call to add a story `story[published] = true` doesn't set the story to be published automatically. I think it could be by design because I don't see it's documented anywhere. 
It's not a bug, please let me know an alternative way to set it publish automatically

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by DominikAngerer** [comment]
Hey there.

Correct `story[published] = true` is by design not available during creation. The way to go would be to use a `GET` request on: `/v1/spaces/space_id/stories/story_id/publish` with the `Authorization` header present - this will trigger the Server-Side Webhooks.

```
curl -X GET \
  https://mapi.storyblok.com/v1/spaces/SPACE_ID/stories/STORY_ID/publish \
  -H 'Cache-Control: no-cache' \
  -H 'authorization: YOUR_AUTH_KEY'
```

We're currently updating the documentations of the management API to let you directly find those additional endpoints.

**Comment by lancevo** [comment]
Thanks! Can I add multiple stories at once? and publish multiple stories at once?

**Comment by DominikAngerer** [comment]
Currently it's only available per Story. Another endpoint is already planed for multi publishing/release planing.
