### ISSUE TITLE
Access token security when using with storyblok-latest.js

### ISSUE THREAD

**Issue by mraerino** [storyblok/storyblok#17]
**The issue occurs while working with:**
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**
- [ ] bug report  
- [ ] feature request  
- [x] question

**Current behavior:**
The behavior in [gatsby boilerplate](https://github.com/storyblok/gatsby-storyblok-boilerplate) will lead to a publicly accessible access token. And this token needs to be able to access drafts to work with the editor. This behavior should not be specific to the gatsby boilerplate though.

**Expected behavior:**
There should be a way to keep the access token secret. What is your recommendation?

The site should not need an access token when used in an iframe inside storyblok. There should be a way for storyblok to pass a temporary access token via a query parameter. Are you planning doing this?

Is there any other strategy you can recommend for keeping the access token secret?

**Comment by DominikAngerer** [comment]
Hey @mraerino thanks for the question.

The Tokens you're mentioned in Preview & Public Tokens are Read-Only tokens that are allowed to be public accessible otherwise one would not be able to directly consume data from a client site. However I understand that using the preview token (that has access to the draft version) may lead to an issue if you do not want to have your draft token available outside of your preview.

## My recommendation:

1. Use an environment variable for that Token
2. Use two different environments:
    - Preview Environment (maybe with latest development version which uses the Preview Token)
    - Production Environment (uses the Public Token)

Doing so you will notice errors faster since your editors will face them during the preview and won't hit publish till that error in your latest development version would be fixed and you never publish your preview token as well.

## Note:

The tokens referred above and used to access content from our [Content Delivery API](https://www.storyblok.com/docs/Delivery-Api/overview) are always *read-only* and are accessible in the Space Settings.

The tokens available in your Profile for our [Management API](https://www.storyblok.com/docs/management-api/authentication) allowing CRUD operations on your spaces should kept secret and only used on server side components.

**Comment by mraerino** [comment]
Thanks for your suggestions.

My plan currently is using a single `/editor` route for the inline preview in storyblok.
This route will be connected to a cloud function that verifies the Storyblok token, loads the editor html and inserts the preview access token. This way it will not be available unless the request comes from inside a Storyblok editor iframe.

*This is possible since Netlify supports an awesome AWS lambda integration*
