### ISSUE TITLE
How can i customize markdown schema?

### ISSUE THREAD

**Issue by kutluhann** [storyblok/storyblok#18]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [ ] feature request  
- [x] question

I want to customize markdown schema. For example add an <a></a> element with a class when I want to attach a link. How can i do it? (Sorry for my English. I hope you understand it :))

**Comment by DominikAngerer** [comment]
Hey there! This highly depends on your Markdown parser. Default Markdown does not have this option - however you can use (depending on your technology) something like kramdown (https://kramdown.gettalong.org/syntax.html#attribute-list-definitions) that allowes you to do that. You can still use the default Markdown field since it will store your information as plain text and send it via the API as plain Markdown. We do use ProseMirror (https://www.storyblok.com/cl/update-rich-text) for our editor interface - however you can use a custom field type if you want to update the interface. I guess you're actually looking for a Parser + Syntax that would support that - so kramdown and it's alternatives would be a good starting point to look at :)

**Comment by DominikAngerer** [comment]
Since Storyblok only is an API and delivers the unprocessed - eg. raw Markdown to you - yes. Something like Kramdown is than used to parse your Markdown to process it to actual HTML :)

**Comment by kutluhann** [comment]
I have one more question. It looks like markdown at source. What can i use for that with nuxt.js?

**Comment by DominikAngerer** [comment]
There are libraries like:

- https://github.com/markedjs/marked
- https://github.com/GitbookIO/kramed
- https://www.npmjs.com/package/markdown
- https://www.npmjs.com/package/@nuxtjs/markdownit

and those can be used with Nuxt either importing it in a component and use it in a method or register a helper plugin and import their functions directly :)
