### ISSUE TITLE
Preview not working in nuxt with router trailingSlash set to true.

### ISSUE THREAD

**Issue by yoann54** [storyblok/storyblok#293]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   in the preview

**Current behavior:**

The preview can't find the page i'm editing.

**Expected behavior:**
I should see the preview of the blog post im editing.

**Steps to reproduce:**
in nuxt.config.js add trailingSlash to true to router option :

**Related code:**
router: {
    trailingSlash: true,
}

**Comment by onefriendaday** [comment]
This is because nuxt is doing a redirect which makes it impossible to detect if the user is in the editmode.  

I'm not aware of any benefit of having a trailing slash in the url. What would be the use case? SEO wise usually it's better to have shorter urls.

You could set it to false or develop a solution to add an exception to not do a redirect if the url has the parameters "_storyblok".

**Comment by yoann54** [comment]
But some company ask for this trailing  slash, it's a demand, thought i neither know if there is a benefit to add it. Anyway i did it outside the router with a regex, i just opened this issue to let u know about this behavior.
