### ISSUE TITLE
May the {"force_update": 1 } be working

### ISSUE THREAD

**Issue by notclickable** [storyblok/storyblok#33]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [X ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ X] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
POSTing an update via API content with {"force_update": 1 } doesn't 'force update' if the component previously had a user-defined slug. Instead, it returns the error 'Unprocessable Entity'. Removing the user-defined slug from the component POST allows {"force_update": 1 } to work as I would expect.

**Expected behavior:**
Using {"force_update": 1 } would update the component even if with a defined slug.

E.g.  POSTing story: { "name": "object name", "slug": "my_defined_slug" ) would be able to be updated if I set {"force_update": 1 }.

**Comment by DominikAngerer** [comment]
Hey there! 

`force_update` is only available on PUT requests. Since you mentioned that you're POSTing components I'm not exactly sure what you're currently doing as it seems that you're actually POSTing stories even tho you want them to update?

PUT on `v1/stories/{ID}` with an object like will work as expected (ignores existing other updates)

```
{
   "story": {
      "id":12345,
      "name":"My Story",
      "slug":"my-story"
   },
   "force_update": 1
}
```

POST will never allow an update.

**Comment by notclickable** [comment]
Sorry, didn't notice I needed to PUT that! I see you need to put the ID in the PUT url too, or it won't work.
