### ISSUE TITLE
Nesting content type components

### ISSUE THREAD

**Issue by hypeJunction** [storyblok/storyblok#51]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [ ] feature request  
- [x] question

**Current behavior:**
I want to create a preview gallery of all stories (e.g. Testimonial, which is set to be a page/content type). If I use `bloks` type, I can create new components of type Testimonial. But how I do allow picking existing ones?

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by hypeJunction** [comment]
Ultimately, the question is, how can I recycle stories across multiple components without having to do a separate API query and/or only including specific stories.

**Comment by DominikAngerer** [comment]
Picking existing entries would be possible with the `multi-option` field type and using `Stories` as source which will allow you to reference stories of another folder (eg. your testimonials). This hower should only be used if you only want to select specific entries and not "all" of them. Here is an example on how this would work for something like "featured posts": https://www.storyblok.com/tp/using-relationship-resolving-to-include-other-content-entries

Since you ultimately would like to create an overview that include all of them without your editors need to select each of them only a API request is currently the best option to go for. The request on the `/stories` endpoint is what you really want to do. This endpoint can be used with the `starts_with` parameter to load stories/entries of one of your folders, eg. `stories?starts_with=testimonals/` and also already handles pagination for you: https://www.storyblok.com/docs/api/content-delivery#topics/pagination

**Comment by hypeJunction** [comment]
Cool. Let me rethink this. I don't want to create a separate nuxt page shell just for this and I want it prerendered. It would be easier if this followed the normal blok pattern, so I don't have to deal with slots and all

**Comment by DominikAngerer** [comment]
This will be much easier with upcoming nuxt versions as you will be able to load data on the server side in a component level rather than only on page level. Will be great! Let me know if you need additional help - closing the issue for now. Feel free to open a new one if you get stuck.

**Comment by hypeJunction** [comment]
Thanks. Will reach out if anything. I have some ideas about improving dev usability of storyblok, I will organise them once I am done with this project
