### ISSUE TITLE
Define a minimum required selection amount of multi option options.

### ISSUE THREAD

**Issue by DominikAngerer** [storyblok/storyblok#57]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

Either required (one) or no check. Currently a check in the implementation itself is the best way to go forward with. 

**Expected behavior:**

Adding a select at least amount x option.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by simonhrogers** [comment]
Here are some quick reasons I think this would be nice but I‘m sure there are more. 

Selecting related items for a product – perhaps you want to do this manually, and need to force the user to select a minimum number because that is what looks good in the UI
Selecting related projects in a portfolio website, same logic

I don’t think this too important compared with the Block issue though which is really a core feature of the CMS and doesn’t allow users to see into blocks as transparently as it should. #52

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/allow-min-and-max-validation
