### ISSUE TITLE
Block inaccessible when trying to add translations at fields level 

### ISSUE THREAD

**Issue by colmanfranco** [storyblok/storyblok#902]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *a.storyblok.com (CMS - Image Service)*
- [ ] *storyblok.com (Website)*
- [ ] *Other:* 

**Current behaviour:**
We are trying to add different translations for our product but when trying to access a block field (to add the necessary translations to the fields inside that block), the block is inaccessible (see picture). Its a strange behaviour because it doesn't happens always and only for some block fields (as you can see in the picture, the Certification details block is accesible but not the About company one).
<img width="402" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/52780288/220101243-acc5905b-9be1-4c11-b39c-e7fba7311923.png">

**Expected behaviour:**
I would expect the same behaviour as with other blocks (to click on it and be able to add the translations for the fields inside).

**Steps to reproduce:**
As I mentioned, is not easy to reproduce because it doesn't always happens and we are unsure why happens for the fields it happens (I was trying to understand if maybe because an issue at the moment of creating the block or something like that).
You can ping me and we can do a showcase so its easier for you to understand what I mean.

**Comment by samuells** [comment]
Hey @colmanfranco, this is indeed strange behavior. We have not received any other reports similar to this one. Is it still happening? Are you able to reproduce it? If so, please contact our support team directly through live chat on [https://www.storyblok.com/](https://www.storyblok.com/) so that they can create a proper internal bug report for it.

Thank you for bringing this to our attention and for your time and effort.
